name: test_workflow
on: push

jobs:
  test_job:
    runs-on: ubuntu-latest
    container: 
      image: endjin.githubactions.powershell:latest
    steps:
    - name: Run test pwsh
      id: run_test_pwsh
      run: |
        echo "::set-output name=abc::def"
        # Get-Input foo
        # Set-Output -Name abc -Value def
      shell: pwsh
      # shell: |
      #   pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"

    - run: echo abc = ${{ steps.run_test_pwsh.outputs.abc}}
      shell: pwsh
      # shell: |
      #   pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
