name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_publish:
        description: When true, the Docker image will be published to DockerHub irrespective of its version
        required: true
        default: false
        type: boolean

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: pwsh -f ./build.ps1

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "PesterTestResults.xml"
