name: publish_to_dockerhub
on:
- push

jobs:
  run_gitversion:
    runs-on: ubuntu-latest
    name: Run GitVersion
    # only trigger for pushed tags
    if: |
      startsWith(github.event.ref, 'refs/tags/')
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
      major: ${{ steps.gitversion.outputs.major }}
      majorMinor: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
      preReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Use GitVersion
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.2

  publish:
    runs-on: ubuntu-latest
    name: Publish to Docker Hub
    needs: run_gitversion
    steps:
    - uses: actions/checkout@v2

    - name: Read workflow configuration
      id: get_config
      run: |
        config=`cat .workflow-config.json`
        echo "::set-output name=configJson::$config"
        MODULE_MANIFEST_PATH=`echo $(jq -r .module_manifest_path <<< $config)`
        echo "::set-output name=module_manifest_path::$MODULE_MANIFEST_PATH"

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ENDJIN_DOCKERHUB_USERNAME  }}
        password: ${{ secrets.ENDJIN_DOCKERHUB_ACCESSTOKEN  }}
        repository: ${{ steps.get_config.outputs.docker_repository }}
        tags: ${{ needs.run_gitversion.outputs.semver }},${{ needs.run_gitversion.outputs.major }},${{ needs.run_gitversion.outputs.majorMinor }}