name: test_workflow
on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    container: 
      image: endjin/endjin.githubactions.powershell:latest
    steps:
    - name: Run test pwsh
      id: run_test_pwsh
      run: |
        echo "::set-output name=abc::def"
        Get-Input foo
        Set-Output -Name abc -Value def
      shell: pwsh

    - run: echo abc = ${{ steps.run_test_pwsh.outputs.abc}}
      shell: pwsh
